source :rubygems

# for rails
gem "rails", "~> 2.3.10"
gem "rack", "~> 1.1.2"
gem "sqlite3-ruby", "1.2.5"
gem "mysql", "2.8.1"
gem "mysql2", "0.2.11"

# passenger 3.0.6 and 3.0.7 weren't working on otto
gem "passenger", "3.0.2"

group :test do
  # For rspec
  gem "rspec", "1.3.2"
  gem "rspec-rails", "1.3.4"
  gem "test-unit", "1.2.3"
  gem "ci_reporter", "1.6.3"

  # For cucumber
  gem "webrat", ">= 0.7.0"
  gem "database_cleaner", ">= 0.5.0"
  gem "cucumber-rails", ">= 0.3.2"
end
